import 'dart:convert';
import 'dart:io';

import 'package:cloud_firestore/cloud_firestore.dart';

/// Synthetic fixture generated by the existing TypeScript V2 validator and
/// supplierImportFinalizationStored serializer. $timestamp is a fixture-only
/// lossless Timestamp tag, not an accepted application wire representation.
Map<String, dynamic> itineraryDraftV2Fixture({bool full = true}) {
  final source =
      jsonDecode(
            File(
              'test/support/itinerary_draft_v2_fixture.json',
            ).readAsStringSync(),
          )
          as Map;
  Object? decode(Object? value) {
    if (value is List) return value.map(decode).toList();
    if (value is Map) {
      if (value.length == 1 && value.containsKey(r'$timestamp')) {
        final parts = value[r'$timestamp'] as List;
        return Timestamp(parts[0] as int, parts[1] as int);
      }
      return value.map((key, value) => MapEntry(key as String, decode(value)));
    }
    return value;
  }

  return Map<String, dynamic>.from(
    decode(source[full ? 'full' : 'minimal']) as Map,
  );
}

Map<String, dynamic> v2At(Map<String, dynamic> data, List<Object> path) {
  dynamic value = data;
  for (final segment in path) {
    value = value[segment];
  }
  return value as Map<String, dynamic>;
}

Map<String, dynamic> v2Package(Map<String, dynamic> data) =>
    v2At(data, ['packageContent']);
Map<String, dynamic> v2Hotel(Map<String, dynamic> data) => v2At(data, [
  'packageContent',
  'accommodations',
  0,
  'options',
  0,
  'details',
]);
Map<String, dynamic> v2Provenance(Map<String, dynamic> data) =>
    v2At(data, ['packageContent', 'inclusions', 0, 'provenance']);
